### ISSUE TITLE
请问如何实现 Json 解析时下化线转驼峰？

### ISSUE THREAD

**Issue by 123lxw123** [xlyasdasd/FlutterJsonHelper#1]
RT

**Comment by xlyasdasd** [comment]
> RT

添加了这个转换，已经提交了plugin,也可以在https://github.com/xlyasdasd/FlutterJsonHelper/blob/master/plugin_flutter_json/plugin_flutter_json.jar
下载jar包提前本地安装

**Comment by 123lxw123** [comment]
![image](https://user-images.githubusercontent.com/20809823/54011972-628cfd00-41af-11e9-9b9e-0d9d2e608807.png)
![image](https://user-images.githubusercontent.com/20809823/54012176-3a51ce00-41b0-11e9-8237-9b7a11957288.png)

**Comment by 123lxw123** [comment]
大佬辛苦了～～，这是哪里还需要设置吗？

**Comment by xlyasdasd** [comment]
> 大佬辛苦了～～，这是哪里还需要设置吗？

可以了，试下最新版
https://github.com/xlyasdasd/FlutterJsonHelper/releases/download/1.2/plugin_flutter_json.jar

**Comment by 123lxw123** [comment]
v 1.2 已经是驼峰风格的了，谢大佬
