### ISSUE TITLE
关于代码来源

### ISSUE THREAD

**Issue by neverwoodsS** [xlyasdasd/FlutterJsonHelper#3]
老哥，虽然我没有加任何 LICENSE，但是你这事干的也太不地道了。
另一方面，感谢你提醒了我应该给自己做的东西加 LICENSE。
既然已经有 LICENSE 了，希望以后不要再出现拿我代码用又不注明的情况了。
更何况你这都不是拿我代码用了，完全是 copy 了我整个项目，自己随便改几个地方就当做自己做的了。还是请你有点追求吧。

**Comment by xlyasdasd** [comment]
抱歉哦，我先说明下情况，1月份，也就是3个多月前，在看flutter，json工具上，下载了你上传的，然而当时的版本并不能在项目中使用（没提供toJSON方法、方法属性命名问题、各种空值报错如List，object, arraylist ），于是我本地做了大量改动，解决上述问题，此时的代码基本只有json字符串与json对象转换工具类是使用你的库里的（后来因为加驼峰也改了），硬要说网上的代码都是不允许别人使用的那我也没办法啊，以后有时间我把里面的那个工具类重构下就是了，不过我会在首页加上感谢链接的。
